/* Clean runtime. The old script is intentionally no longer loaded. */
const app=document.getElementById("app");
const DEV=false;
const norm=s=>(s||"").trim().toLowerCase().replace(/\s+/g,"");
const set=h=>{app.innerHTML=h;if(DEV)dev();window.scrollTo(0,0);window.MathJax?.typesetPromise?.([app]);};
const enter=(id,fn)=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")fn();});
const msg=(id="msg")=>document.getElementById(id);
const val=id=>norm(document.getElementById(id).value);
function burst(word,next){const e=document.createElement("div");e.className=word==="WRONG!"?"bam wrong":"bam";e.textContent=word;document.body.append(e);setTimeout(()=>{e.remove();if(next)next();},700);}
function intro(){set("<h1>No One Asked for This Puzzle</h1><button class='arrow' id='go'>→</button>");document.getElementById("go").onclick=domain;}
function domain(){set("<h2>chapter i — domain</h2><p class='lead'>before applying a map,<br>know where you are.</p><p class='small'>Place each object in its natural home.</p><div class='drag-bank'><div class='drag-token' id='v' draggable='true'>v</div><div class='drag-token' id='w' draggable='true'>ω</div></div><div class='drop-grid'><div class='drop-zone' data-a='v'><p class='small'>tangent space</p><div class='math'>\\[T_pM\\]</div></div><div class='drop-zone' data-a='w'><p class='small'>cotangent space</p><div class='math'>\\[T_p^*M\\]</div></div></div><div class='answer' id='msg'></div>");let n=0;document.querySelectorAll(".drag-token").forEach(x=>x.ondragstart=e=>e.dataTransfer.setData("text/plain",x.id));document.querySelectorAll(".drop-zone").forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=e=>{const id=e.dataTransfer.getData("text/plain");if(id!==z.dataset.a)return msg().textContent="wrong space.";const x=document.getElementById(id);if(!x||z.contains(x))return;z.append(x);x.draggable=false;if(++n===2){msg().innerHTML="good.<br><button id='n'>→</button>";n=document.getElementById("n");n.onclick=flat;}}});}
function flat(){set("<h2>chapter ii — ♭</h2><div class='math'>\\[g=\\begin{pmatrix}2&1\\\\1&1\\end{pmatrix},\\quad v=\\begin{pmatrix}-4\\\\14\\end{pmatrix}\\]</div><p class='lead'>send it to the other side.</p><div class='math'>\\[v^\\flat=\\boxed{\\;?\\;}\\]</div><input id='a' placeholder='covector'><div class='answer' id='msg'></div>");enter("a",()=>{const s=val("a");if(s.includes("6")&&s.includes("10")&&s.includes("dx")&&s.includes("dy")){msg().innerHTML="accepted.<br><button id='n'>→</button>";n.onclick=sharp;}else msg().textContent="check the metric.";});}
function sharp(){set("<h2>chapter ii — ♯</h2><p class='lead'>an inverse exists.<br>use it.</p><div class='math'>\\[h=\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix},\\quad\\beta=26du+43dv\\]</div><div class='math'>\\[\\beta^\\sharp=\\boxed{\\;?\\;}\\]</div><div class='row'><input id='a' placeholder='first coordinate'><input id='b' placeholder='second coordinate'></div><div class='answer' id='msg'></div>");const f=()=>{if(val("a")==="9"&&val("b")==="17"){msg().innerHTML="<div class='math'>\\[p=(6,10),\\quad q=(9,17)\\]</div><button id='n'>→</button>";window.MathJax?.typesetPromise?.([app]);n.onclick=image;}else msg().textContent="use h⁻¹.";};enter("a",f);enter("b",f);}
function image(){set("<h2>chapter iii — image</h2><div class='math center'>\\[gd\\longrightarrow ?\\]</div><p class='small center'>the image depends on the map.</p><input id='a' placeholder='image'><div class='answer' id='msg'></div>");let k=false,g=false;enter("a",()=>{const s=val("a");k||=s==="ㅎㅇ";g||=s.includes("gudermann")||s==="gd(x)";a.value="";if(k&&g){msg().innerHTML="<div class='math'>\\[gd\\xrightarrow{\\text{keyboard}}ㅎㅇ\\qquad gd\\xrightarrow{\\text{analysis}}\\operatorname{gd}\\]</div><p>maps do.</p><button id='n'>→</button>";window.MathJax?.typesetPromise?.([app]);n.onclick=derivative;}else msg().textContent="valid, but incomplete.";});}
function derivative(){set("<h2>chapter iv — discontinuity</h2><div class='math'>\\[u(x)\\]</div><p class='lead'>Differentiate.</p><p class='small'>The unit step function.</p><input id='a'><div class='answer' id='msg'></div>");enter("a",()=>{const s=val("a").replace(/-/g,"");if(["δ","delta","dirac","diracdelta","디렉델타","디랙델타","디랙delta"].includes(s))burst("BAM!!!",()=>{msg().innerHTML="Correct.<p>The Star Trek Theorem.</p><p>Only discontinuities leave a trace.</p><button id='n'>→</button>";n.onclick=caesar;});else msg().textContent="distributionally.";});}
function caesar(){set("<h2>chapter iv — trace</h2><div class='answer-block'>3  1  5  19  1  18</div><p class='small'>Read as A1Z26.</p><input id='a' placeholder='cipher'><div class='answer' id='msg'></div>");enter("a",()=>{if(val("a")!=="caesar")return msg().textContent="the name of a rotation cipher.";msg().innerHTML="<div class='answer-block'>PIITCS ID IWT GTRDGSH</div><p class='small'>67 modulo 26.</p><input id='b' placeholder='plaintext'><div class='answer' id='msg2'></div>";enter("b",()=>{if(val("b").replace(/[^a-z]/g,"")!=="attendtotherecords")return msg("msg2").textContent="rotate by 15.";msg("msg2").innerHTML="accepted.<br><button id='n'>→</button>";n.onclick=recovery;});});}

/* These three maps were generated once, then checked for a unique solution.
   Keeping the verified maps in the game removes all load-time generation. */
const boards=[
  {n:6,map:[[1,1,0,0,0,0],[1,1,1,1,3,0],[2,2,2,1,3,3],[2,5,2,2,3,3],[5,5,5,4,4,4],[5,5,5,4,4,4]],fixed:new Map([[1,2],[5,1],[3,5],[4,3]])},
  {n:8,map:[[0,0,2,1,1,1,1,1],[0,0,2,1,1,3,3,3],[0,0,2,2,2,2,3,3],[0,0,4,4,4,3,3,3],[6,4,4,4,5,3,3,3],[6,4,4,4,5,5,7,7],[6,6,4,5,5,5,7,7],[6,6,4,5,5,5,7,7]],fixed:new Map([[0,1],[7,6],[4,3]])},
  {n:10,map:[[1,1,1,1,0,0,0,0,0,0],[1,1,1,2,2,0,0,0,0,0],[1,2,2,2,2,3,3,3,3,3],[1,4,4,4,3,3,3,3,3,3],[4,4,4,4,4,3,6,3,6,6],[4,7,4,7,4,4,6,6,6,5],[4,7,7,7,7,7,6,6,6,6],[4,7,7,7,7,7,6,6,6,8],[4,7,7,7,8,8,8,8,8,8],[4,7,7,8,8,9,9,9,8,8]],fixed:new Map([[7,3],[0,5]])}
];let level=0;
function violates(board,marks,row,col){const area=board.map[row][col];for(const entry of marks){if(entry[1]!==2)continue;const p=entry[0].split("-").map(Number);if(p[0]===row||p[1]===col||board.map[p[0]][p[1]]===area||(Math.abs(p[0]-row)<=1&&Math.abs(p[1]-col)<=1))return true;}return false;}
function recovery(){
  const board=boards[level],marks=new Map([...board.fixed].map(x=>[x[0]+"-"+x[1],2])),cell=Math.max(29,Math.min(43,Math.floor((window.innerWidth-58)/board.n)));let html="";
  for(let row=0;row<board.n;row++)for(let col=0;col<board.n;col++){const given=board.fixed.get(row)===col;html+="<button class='chi-cell region-"+board.map[row][col]+(given?" given":"")+"' data-row='"+row+"' data-col='"+col+"' data-key='"+row+"-"+col+"'>"+(given?"ㅎㅇ":"")+"</button>";}
  set("<h2>chapter v — recovery / "+(level+1)+"</h2><p class='lead'>one ㅎㅇ belongs in every row,<br>column, and coloured region.</p><p class='small'>No two ㅎㅇs may touch — diagonals count too.<br>Click a square: × → ㅎㅇ → empty.</p><div class='chi-grid' style='grid-template-columns:repeat("+board.n+","+cell+"px)'>"+html+"</div><div class='answer' id='msg'></div>");
  const done=()=>{if([...marks.values()].filter(x=>x===2).length!==board.n)return;const record=level===0?"QUERY\n[ 1  0 ]":level===1?"KEYS\n[ 4  1 ]\n[ 1  3 ]\n[ 3  2 ]":"VALUES\n[ 1  1 ]\n[ 1  2 ]";msg().innerHTML="<p>recovery complete.</p><div class='answer-block'>"+record+"</div><button id='n'>"+(level<2?"next board →":"→")+"</button>";document.getElementById("n").onclick=()=>{if(level<2){level++;recovery();}else attention();};};
  document.querySelectorAll(".chi-cell:not(.given)").forEach(x=>x.onclick=()=>{const key=x.dataset.key,row=Number(x.dataset.row),col=Number(x.dataset.col),next=((marks.get(key)||0)+1)%3;if(next===0){marks.delete(key);x.textContent="";x.classList.remove("note");return;}if(next===1){marks.set(key,1);x.textContent="×";x.classList.add("note");return;}if(violates(board,marks,row,col)){marks.set(key,1);x.textContent="×";x.classList.add("note");burst("WRONG!");return;}marks.set(key,2);x.textContent="ㅎㅇ";x.classList.remove("note");done();});
}
function attention(){set("<h2>chapter v — attention</h2><div class='math'>\\[\\operatorname{Attention}(Q,K,V)=\\operatorname{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V\\]</div><p class='lead'>Attention is all you need.</p><p class='small'>For ordering, softmax changes nothing. The two greatest scores matter.</p><div class='answer-block'>record:  1  2  3  4  5  6  7  8  9  10\nscore:   2  9  1  0  2  4  8  1  3   2</div><div class='row'><input id='a' placeholder='first record'><input id='b' placeholder='second record'></div><div class='answer' id='msg'></div>");const f=()=>{if([val("a"),val("b")].sort().join(",")!=="2,7")return msg().textContent="look only at the two largest scores.";msg().innerHTML="<p>values recovered:</p><div class='math'>\\[K=\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix}\\]</div><button id='n'>→</button>";window.MathJax?.typesetPromise?.([app]);n.onclick=hill;};enter("a",f);enter("b",f);}
function hill(){set("<h2>chapter vi — linear cipher</h2><p class='lead'>The key is linear.</p><div class='math'>\\[K=\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix}\\]</div><div class='answer-block'>PDTZJQSGKH</div><input id='a' placeholder='plaintext'><div class='answer' id='msg'></div><details class='hint'><summary>hint 1</summary><p>Use A=0, B=1, … Z=25. Each pair is a vector in \\(\\mathbb Z_{26}^2\\).</p></details><details class='hint'><summary>hint 2</summary><p>Decrypt by running the map backwards.</p></details><details class='hint'><summary>hint 3</summary><div class='math'>\\[K^{-1}=\\begin{pmatrix}2&25\\\\25&1\\end{pmatrix}\\pmod{26}\\]</div></details>");enter("a",()=>{if(val("a").replace(/[^a-z]/g,"")!=="bongcheon")return msg().textContent="decrypt in pairs.";msg().innerHTML="accepted.<br><button id='n'>→</button>";n.onclick=index;});}
function index(){set("<h2>chapter vii — index</h2><div class='answer-block'>BONGCHEON\n\n1612-14</div><p class='lead'>The index is not numeric.</p><p class='small'>A record can have a location. Find it on the internet.</p><input id='a' placeholder='name recovered from the place'><div class='answer' id='msg'></div>");enter("a",()=>{if(val("a").replace(/[^가-힣]/g,"")!=="이름대로산다")return msg().textContent="search BONGCHEON 1612-14.";msg().innerHTML="<p>NAME RECOVERED.</p><p class='lead'>The name was the instruction.</p><button id='n'>→</button>";n.onclick=diagram;});}
function diagram(){const t=(id,label)=>"<div class='drag-token' id='"+id+"' draggable='true'>"+label+"</div>";set("<h2>chapter viii — a commutative diagram</h2><p class='small'>Place the maps directly on the arrows.</p><div class='drag-bank'>"+t("dgamma","dγ")+t("induced","(γ*g)♭")+t("flat","g♭")+t("pullback","(dγ)*")+"</div><div class='diagram-board'><div class='diagram-node'>\\(T_t[0,1]\\)</div><div class='diagram-slot' data-a='dgamma'>→</div><div class='diagram-node'>\\(T_{\\gamma(t)}\\mathbb R^2\\)</div><div class='diagram-slot vertical' data-a='induced'>↓</div><div></div><div class='diagram-slot vertical' data-a='flat'>↓</div><div class='diagram-node'>\\(T_t^*[0,1]\\)</div><div class='diagram-slot' data-a='pullback'>←</div><div class='diagram-node'>\\(T_{\\gamma(t)}^*\\mathbb R^2\\)</div></div><div class='answer' id='msg'></div>");let placed=0;document.querySelectorAll(".drag-token").forEach(x=>x.ondragstart=e=>e.dataTransfer.setData("text/plain",x.id));document.querySelectorAll(".diagram-slot").forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=e=>{const id=e.dataTransfer.getData("text/plain");if(id!==z.dataset.a)return msg().textContent="That map does not belong there.";const x=document.getElementById(id);if(!x||z.contains(x))return;z.append(x);x.draggable=false;if(++placed===4){msg().innerHTML="<p>The diagram commutes.</p><div class='math'>\\[p=(6,10),\\quad q=(9,17)\\]</div><button id='n'>→</button>";window.MathJax?.typesetPromise?.([app]);n.onclick=calendar;}}});}
function calendar(){set("<h2>chapter ix — closed</h2><p class='lead'>The points are correct.<br>The space is not.</p><div class='math'>\\[(6,10)\\mapsto06/10\\qquad(9,17)\\mapsto09/17\\]</div><p class='small'>Count the closed interval, not the distance.</p><input id='a' placeholder='value'><div class='answer' id='msg'></div>");enter("a",()=>{if(val("a")!=="100")return msg().textContent="you lost a day.";msg().innerHTML="<p>the diagram commutes.</p><div class='math'>\\[\\square\\]</div><button id='n'>appendix 6.7</button>";window.MathJax?.typesetPromise?.([app]);n.onclick=appendix;});}
function appendix(){set("<h2>appendix 6.7</h2><div class='math'>\\[K_{67}(x)=\\frac{67}{2\\pi}[\\operatorname{gd}(67x+1)-\\operatorname{gd}(67x-1)]\\]</div><p class='lead'>This appendix is unnecessary.</p><p>There are simpler ways to celebrate 100 days.</p><p>This one also works.</p><button id='n'>∎</button>");n.onclick=finale;}
function finale(){set("<div class='center' style='padding-top:18vh'><button id='g' style='font-size:42px;text-decoration:none'>gd</button><div id='f' class='hidden'><div class='math'>\\[gd\\xrightarrow{\\;us\\;}ㅎㅇ\\]</div><p class='lead'>100일 축하해</p><p class='footer-note'>the final object is not on this page.<br>가방 안을 봐.</p></div></div>");document.getElementById("g").onclick=()=>{document.getElementById("f").classList.remove("hidden");document.getElementById("g").remove();window.MathJax?.typesetPromise?.([app]);};}
const screens=[["I. domain",domain],["II. flat",flat],["II. sharp",sharp],["III. image",image],["IV. derivative",derivative],["IV. caesar",caesar],["V. recovery",recovery],["V. attention",attention],["VI. Hill cipher",hill],["VII. index",index],["VIII. diagram",diagram],["IX. closed",calendar],["appendix",appendix],["finale",finale]];
function dev(){app.insertAdjacentHTML("beforeend","<details class='dev-tools'><summary>developer tools</summary><label for='dev-screen'>jump to a problem</label><select id='dev-screen'>"+screens.map((s,i)=>"<option value='"+i+"'>"+s[0]+"</option>").join("")+"</select><p>Development only — remove before publishing.</p></details>");document.getElementById("dev-screen").onchange=e=>screens[e.target.value][1]();}
intro();
